import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats
{
	public static void main (String[] args)
	{
		// Gets the two command-line arguments
		int T1=Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you had a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		
		
		int countn=0;
		int num2c=0;
		int num3c=0;
		int num4plusc=0;
		boolean t=false;
		boolean s=false;
		double total=0;

		for (int i=0; i<T1; i++)
		{
			countn=0;
			t=false;
			s=false;
			
			while(t==false||s==false)
			{
				double rnd=generator.nextDouble();
				if(rnd>=.5)
				{
					countn++;
					t=true;
				}
				else
				{
					countn++;
					s=true;
				}	
			}
			if (countn==2)
				num2c++;
			else
			{
				if (countn==3)
					num3c++;
				else
					num4plusc++;
					
			}
		total=total+countn;	
			
		}
		
		
		double avg= (double)(total/T1);
		System.out.println("Average: " + avg + " children to get at least one of each gender.");

		
		System.out.println("Number of families with 2 children: " + num2c);	
		System.out.println("Number of families with 3 children: " + num3c);	
		System.out.println("Number of families with 4 or more children: " + num4plusc);
		
		if(num2c>num3c&&num2c>num4plusc)
			System.out.println("The most common number of children is 2.");
		if (num3c>num4plusc&&num3c>num2c)
			System.out.println("The most common number of children is 3. ");
		if(num4plusc>num2c&&num4plusc>num3c)
			System.out.println("The most common number of children is 4 of more. ");
		if (num2c==num3c&&num2c==num4plusc&&num3c==num4plusc)
			System.out.println("The most common number of children is 2. ");
		if(num3c==num4plusc&&num3c!=num2c&&num3c>num2c)
			System.out.println("The most common number of children is 3. ");
		if(num2c==num3c&&num2c!=num4plusc&&num2c>num4plusc)
			System.out.println("The most common number of children is 2. ");
		if(num2c==num4plusc&&num2c!=num3c&&num2c>num3c)
			System.out.println("The most common number of children is 2. ");
				
		
		
		
		    
	}
}
